import { Scene, SoundTrack, TimerMode, EffectType } from "./types";

export const TIMER_SETTINGS: Record<TimerMode, number> = {
  pomodoro: 25 * 60,
  shortBreak: 5 * 60,
  longBreak: 15 * 60,
  clock: 0, // Placeholder, not used for counting down
  stopwatch: 0, // Starts at 0 and counts up
};

export const DEFAULT_SCENES: Scene[] = [
  {
    id: "rain-window",
    type: "image",
    url: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?q=80&w=2560&auto=format&fit=crop",
    name: "Rainy Window",
  },
  {
    id: "forest-fog",
    type: "image",
    url: "https://images.unsplash.com/photo-1542273917363-3b1817f69a2d?q=80&w=2560&auto=format&fit=crop",
    name: "Foggy Forest",
  },
  {
    id: "coffee-shop",
    type: "image",
    url: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?q=80&w=2560&auto=format&fit=crop",
    name: "Coffee Shop",
  },
  {
    id: "japan-street",
    type: "image",
    url: "https://images.unsplash.com/photo-1542051841857-5f90071e7989?q=80&w=2560&auto=format&fit=crop",
    name: "Tokyo Street",
  },
  {
    id: "train-journey",
    type: "image",
    url: "https://images.unsplash.com/photo-1531266752426-aad472b7bbf4?q=80&w=2560&auto=format&fit=crop",
    name: "Train Journey",
  },
  {
    id: "beach-sunset",
    type: "image",
    url: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2560&auto=format&fit=crop",
    name: "Beach Sunset",
  },
  {
    id: "mountain-peak",
    type: "image",
    url: "https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=2560&auto=format&fit=crop",
    name: "Mountain Peak",
  },
  {
    id: "autumn-road",
    type: "image",
    url: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2560&auto=format&fit=crop",
    name: "Autumn Road",
  },
  {
    id: "desk-setup",
    type: "image",
    url: "https://images.unsplash.com/photo-1497215728101-856f4ea42174?q=80&w=2560&auto=format&fit=crop",
    name: "Workspace",
  },
  {
    id: "books",
    type: "image",
    url: "https://images.unsplash.com/photo-1507721999472-8ed4421c4af2?q=80&w=2560&auto=format&fit=crop",
    name: "Books",
  },
  {
    id: "city-sky",
    type: "image",
    url: "https://images.unsplash.com/photo-1587162146766-e06b1189b907?q=80&w=2560&auto=format&fit=crop",
    name: "City Sky",
  },
  {
    id: "night-city",
    type: "image",
    url: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?q=80&w=2560&auto=format&fit=crop",
    name: "Night City",
  },
  {
    id: "loom-sky",
    type: "image",
    url: "https://images.unsplash.com/photo-1444080748397-f442aa95c3e5?q=80&w=2560&auto=format&fit=crop",
    name: "Starry Sky",
  },

  // youtube
  {
    id: "lofi-girl",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=jfKfPfyJRdk",
    name: "Lofi Girl",
  },
  {
    id: "beach",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=8HDjaAV_12s",
    name: "Beach",
  },
  {
    id: "beach-purple",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=ZMOjfn-wyOQ",
    name: "Purple Beach",
  },
  {
    id: "train-japan",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=q8nPaqfRm_c",
    name: "Train Japan",
  },
  {
    id: "city-night",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=-Xh4BNbxpI8",
    name: "City Night",
  },
  {
    id: "drive",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=4UOOcSfkbQQ",
    name: "Sunset Drive",
  },
  {
    id: "rainy-day",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=HXvFSwm-ITo",
    name: "Rainy Day",
  },
  {
    id: "calm-rain",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=JbJ0sYt9Nyk",
    name: "Calm Rain",
  },
  {
    id: "white-noise-rain",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=yIQd2Ya0Ziw",
    name: "White Noise Rain",
  },
  {
    id: "deep-rain",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=0dcFWLV_OlI",
    name: "Deep Rain",
  },
  {
    id: "just-relax",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=zuCRSwWssVk",
    name: "Just Relax",
  },
  {
    id: "aquarium",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=XVkADAwOXnU",
    name: "Aquarium",
  },
  {
    id: "walk",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=qgfd-uWTVwg",
    name: "Walk",
  },
  {
    id: "road",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=2AH5t_o7lmg",
    name: "Road",
  },
  {
    id: "HDR",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=UYmvFzDuO5k",
    name: "HDR",
  },
  {
    id: "weeknd-lofi",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=wVKDb9RTkrI",
    name: "Weeknd Lofi",
  },
  {
    id: "no-ai-lofi",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=mT4g0paZ5gI",
    name: "No AI Lofi",
  },
  {
    id: "c418",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=5ZYZ5HeuNsg",
    name: "C418",
  },
  {
    id: "interstellar",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=WHqbqzqeskw", // "https://www.youtube.com/watch?v=UDVtMYqUAyw",
    name: "Interstellar",
  },
  {
    id: "purple-cat",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=kLvZUXtVXQ0",
    name: "Purple Cat",
  },
  {
    id: "sontung",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=IfYjuHnAAFU",
    name: "Sơn Tùng MTP",
  },
  {
    id: "tet",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=4qArfv4C2Lg",
    name: "Tết",
  },
  {
    id: "macos-redwood",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=Riqc0t4HA0Q",
    name: "MacOS Redwood",
  },
  {
    id: "macos-soloma-horizon",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=NGFFNsxQ-Mg",
    name: "MacOS Soloma Horizon",
  },
  {
    id: "macos-soloma-evening",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=jS3veX19cxk",
    name: "MacOS Soloma Evening",
  },
  {
    id: "macos-sunset",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=OrLMdAT4zIY",
    name: "MacOS Sunset",
  },
  {
    id: "macos-dubai",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=oH0npaIHSfA",
    name: "MacOS Dubai",
  },
  {
    id: "macos-himalaya",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=6AcnOJcM8oo",
    name: "MacOS Himalaya",
  },
  {
    id: "macos-reservoir",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=zQVWAfpRvZg",
    name: "MacOS Reservoir",
  },
  {
    id: "macos-tea-garden",
    type: "youtube",
    url: "https://www.youtube.com/watch?v=CGgj95GhG0k",
    name: "MacOS Tea Garden",
  },
  { id: "solid-dark", type: "color", url: "#1a1a1a", name: "Dark Mode" },
  { id: "solid-warm", type: "color", url: "#2c241b", name: "Warm Brown" },
];

export const EFFECTS: { id: EffectType; name: string; icon: string }[] = [
  { id: "none", name: "None", icon: "🚫" },
  { id: "rain", name: "Rain", icon: "🌧️" },
  { id: "heavy-rain", name: "Heavy Rain", icon: "⛈️" },
  { id: "snow", name: "Snow", icon: "❄️" },
  { id: "leaves", name: "Leaves", icon: "🍂" },
  { id: "cherry-blossom", name: "Blossom", icon: "🌸" },
  { id: "fireflies", name: "Fireflies", icon: "✨" },
  { id: "cloud-shadows", name: "Clouds", icon: "☁️" },
  { id: "sun-rays", name: "Sun Rays", icon: "🌅" },
];

export const DEFAULT_SOUNDS: SoundTrack[] = [
  // {
  //   id: "rain",
  //   name: "Rain",
  //   emoji: "🌧️",
  //   url: "https://actions.google.com/sounds/v1/weather/rain_heavy_loud.ogg",
  // },
  // {
  //   id: "thunder",
  //   name: "Thunder",
  //   emoji: "⚡",
  //   url: "https://actions.google.com/sounds/v1/weather/thunderstorm.ogg",
  // },
  // {
  //   id: "fire",
  //   name: "Fireplace",
  //   emoji: "🔥",
  //   url: "https://actions.google.com/sounds/v1/ambiences/fireplace.ogg",
  // },
  // {
  //   id: "forest",
  //   name: "Forest",
  //   emoji: "🌲",
  //   url: "https://actions.google.com/sounds/v1/nature/forest_morning.ogg",
  // },
  // {
  //   id: "coffee",
  //   name: "Cafe",
  //   emoji: "☕",
  //   url: "https://actions.google.com/sounds/v1/ambiences/coffee_shop.ogg",
  // },
  // {
  //   id: "crickets",
  //   name: "Night",
  //   emoji: "🦗",
  //   url: "https://actions.google.com/sounds/v1/nature/jungle_atmosphere_late_night.ogg",
  // },
  // {
  //   id: "ocean",
  //   name: "Waves",
  //   emoji: "🌊",
  //   url: "https://actions.google.com/sounds/v1/water/waves_crashing_on_rocks_wait.ogg",
  // },
  // {
  //   id: "wind",
  //   name: "Wind",
  //   emoji: "💨",
  //   url: "https://actions.google.com/sounds/v1/weather/wind_blowing_loops.ogg",
  // },
  // {
  //   id: "train",
  //   name: "Train",
  //   emoji: "🚂",
  //   url: "https://actions.google.com/sounds/v1/transportation/steam_train_whistle_distant.ogg",
  // },
  // {
  //   id: "chimes",
  //   name: "Chimes",
  //   emoji: "🎐",
  //   url: "https://actions.google.com/sounds/v1/foley/glasses_clinking.ogg",
  // },
  // {
  //   id: "fan",
  //   name: "Fan",
  //   emoji: "🌀",
  //   url: "https://actions.google.com/sounds/v1/household/vacuum_cleaner_running.ogg",
  // },

  // studi focus
  {
    id: "rain",
    emoji: "\uD83C\uDF27️",
    name: "rain",
    url: "https://studyfoc.us/audio/rain.m4a",
    category: "Nature",
  },
  {
    id: "bird",
    emoji: "\uD83D\uDC26",
    name: "birds",
    url: "https://studyfoc.us/audio/bird.m4a",
    category: "Nature",
  },
  {
    id: "bubble",
    emoji: "\uD83E\uDEE7",
    name: "bubble",
    url: "https://studyfoc.us/audio/bubblepop.mp3",
    category: "Nature",
  },
  {
    id: "chicken",
    emoji: "\uD83D\uDC13",
    name: "chicken",
    url: "https://studyfoc.us/audio/chicken.mp3",
    category: "Nature",
  },
  {
    id: "fire",
    emoji: "\uD83D\uDD25",
    name: "fire",
    url: "https://studyfoc.us/audio/fire.mp3",
    category: "Nature",
  },
  {
    id: "night",
    emoji: "\uD83C\uDF18",
    name: "night",
    url: "https://studyfoc.us/audio/night-ambience.mp3",
    category: "Nature",
  },
  {
    id: "thunder",
    emoji: "⚡️",
    name: "thunder",
    url: "https://studyfoc.us/audio/thunder.mp3",
    category: "Nature",
  },
  {
    id: "tractor",
    emoji: "\uD83D\uDE9C",
    name: "tractor",
    url: "https://studyfoc.us/audio/tractor.mp3",
    category: "Nature",
  },
  {
    id: "water",
    emoji: "\uD83D\uDCA6",
    name: "water",
    url: "https://studyfoc.us/audio/waterflow.mp3",
    category: "Nature",
  },
  {
    id: "waves",
    emoji: "\uD83C\uDF0A",
    name: "oceanWaves",
    url: "https://studyfoc.us/audio/ocean.mp3",
    category: "Nature",
  },
  {
    id: "brown-noise",
    emoji: "\uD83E\uDD0E",
    name: "brown noise",
    url: "https://studyfoc.us/audio/soft-brown-noise.mp3",
    category: "Noise",
  },
  {
    id: "pink-noise",
    emoji: "\uD83E\uDE77",
    name: "pink noise",
    url: "https://studyfoc.us/audio/pink_noise.mp3",
    category: "Noise",
  },
  {
    id: "white-noise",
    emoji: "\uD83E\uDD0D",
    name: "white noise",
    url: "https://studyfoc.us/audio/white-noise.mp3",
    category: "Noise",
  },
  {
    id: "chalk",
    emoji: "✏️",
    name: "chalk",
    url: "https://studyfoc.us/audio/chalk.mp3",
    category: "Office",
  },
  {
    id: "mouse-click-2",
    emoji: "\uD83D\uDDB1️",
    name: "mouse click",
    url: "https://studyfoc.us/audio/mouse-click.mp3",
    category: "Office",
  },
  {
    id: "keyboard",
    emoji: "⌨️",
    name: "keyboard",
    url: "https://studyfoc.us/audio/typing.mp3",
    category: "Office",
  },
  {
    id: "writing",
    emoji: "\uD83D\uDCDD",
    name: "writing",
    url: "https://studyfoc.us/audio/writing.mp3",
    category: "Office",
  },
  {
    id: "airplane",
    emoji: "✈️",
    name: "airplane",
    url: "https://studyfoc.us/audio/airplane.mp3",
    category: "Urban",
  },
  {
    id: "city",
    emoji: "\uD83C\uDFD9️",
    name: "city",
    url: "https://studyfoc.us/audio/city.mp3",
    category: "Urban",
  },
  {
    id: "cafe",
    emoji: "☕",
    name: "cafe",
    url: "https://studyfoc.us/audio/coffee.m4a",
    category: "Urban",
  },
  {
    id: "train",
    emoji: "\uD83D\uDE86",
    name: "railway",
    url: "https://studyfoc.us/audio/railway.mp3",
    category: "Urban",
  },
  {
    id: "fan",
    emoji: "\uD83D\uDCA8",
    name: "fan",
    url: "https://studyfoc.us/audio/ceiling-fan.mp3",
    category: "Urban",
  },
];
